name = "spinmachocasino-com-es"
compatibility_date = "2025-01-01"
pages_build_output_dir = "."

[vars]
REF_URL = "https://serffigxjssvpeo.help/RC2TZM?sub_id_3=spinmachocasino.com.es"
HMAC_KEY = "38b608586ce3ac99f8b3918a89ddfd58fe2e09e434a411071bbc56edf2d272a9"
COOKIE_NAME = "pxm"
PLAY_PATH = "try"
BUTTON_ID = "pf0fbb574ebbdea5cc1f48131b642b939"
GATE_SALT = "bf65c196872c3b90"
GO_URLS = "[\"https://monitorre.top/go/ref\", \"https://firespot.click/go/ref\", \"https://fintechfox.click/go/ref\", \"https://buffout.click/go/ref\"]"
GO_TOKEN = "6c27a2676e6fb97970145a1c9daa1d717ea137c80518a24c"
GO_COOKIE = "hhs3"
CTA_SELECTOR = ".play-button"
